name: Run rsltc on .rsl specs
run-name: ${{ github.actor }} is running rsltc on some .rsl spec files
on: [push]
jobs:
  Install-And-Run-rsltc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Cloned ${{ github.repository }} to runner."
      - name: Add i386 architecture for 32-bit support
        run: sudo dpkg --add-architecture i386 && sudo apt update
      - name: Install dependencies
        run: sudo apt install -y smlnj texlive-base m4
      - name: Install rsltc
        run: sudo dpkg -i deb/rsltc_2.6.1-1_i386.deb
      - run: echo "Installation complete! This job's status is ${{ job.status }}."
      - name: Run rsltc on spec files
        run: chmod +x ./run_rsltc.sh && ./run_rsltc.sh
      - name: Run test on generated sml
        run: chmod +x ./run_sml.sh && ./run_sml.sh
      - name: Run cleanup on generated files
        run: chmod +x ./run_cleanup.sh && ./run_cleanup.sh
